### ISSUE TITLE
Shader "parameters"

### ISSUE THREAD

**Issue by theChaosCoder** [Lypheo/vs-placebo#5]
Some shaders have "parameters" like:

```
#define INTENSITY_SIGMA 0.1 //Intensity window size, higher is stronger denoise, must be a positive real number
#define SPATIAL_SIGMA 1.0 //Spatial window size, higher is stronger denoise, must be a positive real number
```
https://github.com/bloc97/Anime4K/tree/master/glsl

Is it possible to change those parameters on the fly with placebo.Shader()? If not, would it be hard to implement?

**Comment by Lypheo** [comment]
No, in the general case, there is no way of knowing which #defines are supposed to be tunable parameters. And even if there was, I can't think of a way to pass those parameters to placebo.Shader() that isn't horribly ugly. What I could implement, though, is passing the shader directly as a string instead of a filename. That way, you could implement your own tunable shader generators in python.

**Comment by theChaosCoder** [comment]
I will take that, better than nothing. Some string replacement will do the rest.
